sonar.projectKey=RazvanMV1_ai-tutor
sonar.organization=razvanmv1
sonar.projectName=AI-Enhanced Tutor
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/Migrations/**,**/bin/**,**/obj/**,**/__pycache__/**,**/venv/**

sonar.python.coverage.reportPaths=src/ai-module/coverage.xml
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
