events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /index.html {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }

        location ~* \.(js|wasm|dll|dat|blat|pdb)$ {
            types {
                application/javascript js;
                application/wasm wasm;
                application/octet-stream dll dat blat pdb;
            }

            try_files $uri =404;

            location ~* \.gz$ {
                add_header Content-Encoding gzip;
            }

            location ~* \.br$ {
                add_header Content-Encoding br;
            }
        }
    }
}